# Business Vertical Deals Table

## As is

There are one sheets for the deals for the business veritcal:

- Company Name	
    - Unique now but will have an id
- Project Name	
    - Most is empty - ask about this one
- Date Added
    - Initial deal date
- Invest. Bank	
    - Can be multiple banks involved in a deal
- Banker
    - Empty
    - Can enrich data later once data models are set
- Sourcing
    - 3 types: ['Auction' 'Trusted Netwok' 'Proprietary']
- Transaction Type
    - 3 types: ['Sponsor to Sponsor' 'Corporate Seller' 'Other Private Buyout'
 'Corporate Seller ' nan]
    - Data cleansing is required - will remove leading and laging white space from all columns
- LTM Revenue
    - Empty 
- LTM EBITDA	
    - Empty but has (LTM) in other columns
    - Last Twelve Month, clarify if we pivot the data can we remove? Or we can make it a flaged value?
- 2014A EBITDA
    - Pivot
    - What do we do with estimates - do we want a new flag column
    - Curency column to remove from values
    - net income, pre tax info what to do with that
- 2015A EBITDA	
    - Pivot
- 2016A EBITDA	
    - Pivot
- 2017A/E EBITDA
    - Pivot
- 2018E EBITDA
    - Pivot
- Vertical	
    - Not needed in deals
- Sub Vertical	
    - Not needed in deals
- Enterprise Value	
    - calculation: Takes the most recent EBITDA and multiplies by 10 - only for last two years
    - clarify how it is calculated
- Equity Investment Est.
    - calculation: divides enterprise value by 2 when it is a sponsor to sponser transaction
- Status	
    - 4 types:['Active' 'Dead' nan 'Closed By THL' 'On Hold']
- Current Owner	
    - Capital management companies - Do we want in contacts eventually
- Business Description
    - Stretch is to group under umbrella descriptions so there is less free text
- Lead MD
    - 6 distinct MDs


## To be

This table should be the deals table. 
- Deal id (deal unique identifier)
- Company ID (FK)
- Project Name
- Year
- Month
- Day
- Investment Bank
- Banker - will need to fill
- sourcing
- Transaction type
- Status
- Current Owner - Thinking this should be in contacts
- Business Description
    - Stretch is to group under umbrella descriptions so there is less free text
    - Also thinking of adding this and the compnay to contacts
- Lead MD


These will be in a finance table
- Revenue - can be web scapped if needed
- EBITDA
- Enterprise Value	
    - calculation: Takes the most recent EBITDA and multiplies by 10 - only for last two years
    - clarify how it is calculated
- Equity Investment Est.
    - calculation: divides enterprise value by 2 when it is a sponsor to sponser transaction

In [1]:
import pandas as pd

In [9]:
path = "..\data\Business Services Pipeline.xlsx"
bus_pipeline = pd.read_excel(path, skiprows=5) # Headers at 5 data at 6

In [10]:
display(bus_pipeline)

,Company Name,Project Name,Date Added,Invest. Bank,Banker,Sourcing,Transaction Type,LTM Revenue,LTM EBITDA,2014A EBITDA,...,2017A/E EBITDA,2018E EBITDA,Vertical,Sub Vertical,Enterprise Value,Equity Investment Est.,Status,Current Owner,Business Description,Lead MD
0,Shermco,NaN,2018-02-02 00:00:00,Harris Williams,NaN,Auction,Sponsor to Sponsor,NaN,NaN,NaN,...,26.7,NaN,Business Services,"Testing, Inspection & Certificaiton",267,133.5,Active,Oaktree,"Electrical testing, maintenance, and commissio...",Jeannie Blackwood
1,Kastle Systems,NaN,2018-02-02 00:00:00,NaN,NaN,Trusted Netwok,Sponsor to Sponsor,NaN,NaN,NaN,...,NaN,NaN,Business Services,Facilities Services,NaN,NaN,Active,Venturehouse,"Provider of comprehensive, turnkey security so...",Andrew Mah
2,CLEAResult,NaN,2018-02-02 00:00:00,NaN,NaN,Trusted Netwok,Sponsor to Sponsor,NaN,NaN,NaN,...,NaN,NaN,Business Services,Facilities Services,NaN,NaN,Active,General Atlantic,Provider of energy efficiency and demand manag...,Kripa Shah
3,PLH,NaN,2018-02-02 00:00:00,Barclays,NaN,Auction,Sponsor to Sponsor,NaN,NaN,NaN,...,68,NaN,Business Services,Industrial & Environmental Services,680,340.0,Active,Energy Capital Partners,Specialty contractor serving the electric powe...,Russ Barner
4,BBB Industries,NaN,2018-02-02 00:00:00,"Baird, Jefferies",NaN,Auction,Sponsor to Sponsor,NaN,NaN,NaN,...,100,NaN,Business Services,Specialty Distribution,1000,500.0,Active,Pamplona,Provider of remanufactured replacement parts t...,Matthew Kordonowy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,DH Corporation,NaN,Nov-16,Take-private,NaN,Auction,Corporate Seller,NaN,NaN,NaN,...,CAD 330,NaN,Business Services,Financial Technology,"CAD $3,474",NaN,Dead,Finastra,Financial technology,Russ Barner
124,National Response Corporation (NRC),NaN,Nov-16,Harris Williams,NaN,Auction,Sponsor to Sponsor,NaN,NaN,NaN,...,35,NaN,Business Services,"Testing, Inspection & Certificaiton",350,175.0,Dead,JF Lehman,Compliance and environmental services,Matthew Kordonowy
125,SunGard Insurance,NaN,Oct-16,Direct to Company,NaN,Proprietary,Corporate Seller,NaN,NaN,NaN,...,68,NaN,Business Services,Financial Technology,680,NaN,Dead,FIS,Insurance software provider,Andrew Mah
126,PSG,NaN,Sep-16,Centerview,NaN,Auction,Other Private Buyout,NaN,NaN,NaN,...,NaN,NaN,Business Services,Specialty Distribution,NaN,NaN,Dead,"Sagard Holdings, Fairfax Capital",Sporting goods,Kripa Shah
127,World Business Lenders,NaN,Sep-16,NaN,NaN,Auction,Sponsor to Sponsor,NaN,NaN,NaN,...,NaN,NaN,Business Services,Banks / Lending,NaN,NaN,Dead,AR Capital,Small business lender,Russ Barner

In [ ]:
bus_pipeline.info() # Banker should not be float, some ebitda come in as strings

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Company Name            127 non-null    object
 1   Project Name            1 non-null      object
 2   Date Added              127 non-null    object
 3   Invest. Bank            112 non-null    object
 4   Banker                  0 non-null      float64
 5   Sourcing                128 non-null    object
 6   Transaction Type        122 non-null    object
 7   LTM Revenue             0 non-null      float64
 8   LTM EBITDA              0 non-null      float64
 9   2014A EBITDA            33 non-null     object
 10  2015A EBITDA            41 non-null     object
 11  2016A EBITDA            63 non-null     object
 12  2017A/E EBITDA          72 non-null     object
 13  2018E EBITDA            2 non-null      float64
 14  Vertical                128 non-null    object
 15  Sub Vertical            128 non-null    object
 16  Enterprise Value        78 non-null     object
 17  Equity Investment Est.  52 non-null     float64
 18  Status                  126 non-null    object
 19  Current Owner           122 non-null    object
 20  Business Description    127 non-null    object
 21  Lead MD                 128 non-null    object
dtypes: float64(5), object(17)
memory usage: 22.1+ KB

In [11]:
bus_pipeline.describe()

       Banker  LTM Revenue  LTM EBITDA  2018E EBITDA  Equity Investment Est.
count     0.0          0.0         0.0      2.000000               52.000000
mean      NaN          NaN         NaN     45.000000              327.095192
std       NaN          NaN         NaN     21.213203              241.386489
min       NaN          NaN         NaN     30.000000               18.200000
25%       NaN          NaN         NaN     37.500000              138.625000
50%       NaN          NaN         NaN     45.000000              250.000000
75%       NaN          NaN         NaN     52.500000              473.750000
max       NaN          NaN         NaN     60.000000             1025.000000

In [13]:
string_data_only = bus_pipeline.drop(["Banker", "LTM Revenue", "LTM EBITDA", "2018E EBITDA", "Equity Investment Est."], axis = 1)

In [14]:
string_data_only.describe()

,Company Name,Project Name,Date Added,Invest. Bank,Sourcing,Transaction Type,2014A EBITDA,2015A EBITDA,2016A EBITDA,2017A/E EBITDA,Vertical,Sub Vertical,Enterprise Value,Status,Current Owner,Business Description,Lead MD
count,127,1,127,112,128,122,33.0,41,63,72,128,128,78,126,122,127,128
unique,127,1,45,43,3,4,32.0,37,57,63,1,21,60,4,102,116,6
top,Shermco,Project Ignition,2018-02-02 00:00:00,Direct to Company,Auction,Sponsor to Sponsor,14.7,22,50,30,Business Services,Industrial & Environmental Services,300,Dead,Privately Held,Merchant acquirer,Jeannie Blackwood
freq,1,1,11,14,106,84,2.0,2,2,4,128,23,5,92,8,4,72

In [15]:
print(string_data_only["Sourcing"].unique())

['Auction' 'Trusted Netwok' 'Proprietary']

In [16]:
print(string_data_only["Transaction Type"].unique())

['Sponsor to Sponsor' 'Corporate Seller' 'Other Private Buyout'
 'Corporate Seller ' nan]

In [17]:
print(string_data_only["Status"].unique())

['Active' 'Dead' nan 'Closed By THL' 'On Hold']